/** @type {import('stylelint').Config} */
export default {
  extends: [
    "stylelint-config-standard",
    "stylelint-config-alphabetical-order",
    "@stylistic/stylelint-config",
    "stylelint-plugin-logical-css/configs/recommended",
  ],
  plugins: [
    "stylelint-plugin-logical-css",
    "stylelint-use-nesting",
    "stylelint-high-performance-animation",
    "@stylistic/stylelint-plugin",
    "stylelint-declaration-block-no-ignored-properties",
    "stylelint-media-use-custom-media",
    "stylelint-value-no-unknown-custom-properties",
  ],
  reportUnscopedDisables: true,
  reportInvalidScopeDisables: true,
  reportNeedlessDisables: true,
  rules: {
    "color-named": "never",
    "function-disallowed-list": ["rgb", "hwb", "lch", "hsl"],
    "selector-max-id": 0,
    "color-no-invalid-hex": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-no-unknown": true,
    "no-unknown-animations": true,
    "no-unknown-custom-media": true,
    "no-unknown-custom-properties": true,
    "unit-no-unknown": true,
    "display-notation": "short",
    "font-weight-notation": "numeric",
    "csstools/use-nesting": true,
    "plugin/no-low-performance-animation-properties": true,
    "plugin/declaration-block-no-ignored-properties": true,
    "csstools/media-use-custom-media": true,
    "csstools/value-no-unknown-custom-properties": true,
  },
};
